In [1]:
import numpy as np
import pandas as pd
from scipy import stats

VARIANT = 8
CITY = "Poltava"
REGION = "Center"
ALPHA = 0.05

poltava = np.array([
    84, 81, 76, 69, 63, 61,
    59, 61, 67, 74, 80, 85
])

kyiv = np.array([
    84, 82, 78, 70, 65, 63,
    61, 63, 68, 75, 81, 85
])

lviv = np.array([
    85, 83, 80, 73, 68, 65,
    63, 65, 70, 77, 82, 86
])

odesa = np.array([
    82, 80, 78, 74, 71, 69,
    67, 68, 72, 76, 80, 83
])

print("Variant:", VARIANT)
print("City:", CITY)
print("Region:", REGION)
print("Alpha:", ALPHA)

Variant: 8
City: Poltava
Region: Center
Alpha: 0.05


In [2]:
norm = 72

t_stat_1, p_value_1 = stats.ttest_1samp(
    poltava,
    popmean=norm
)

print("Sample mean:", poltava.mean())
print("Sample standard deviation:", poltava.std(ddof=1))
print("Norm:", norm)
print("t-statistic:", t_stat_1)
print("p-value:", p_value_1)

Sample mean: 71.66666666666667
Sample standard deviation: 9.547330263037681
Norm: 72
t-statistic: -0.12094486171172247
p-value: 0.9059156763414993


In [3]:
x_bar = poltava.mean()
s = poltava.std(ddof=1)
n = len(poltava)

t_manual = (x_bar - norm) / (s / np.sqrt(n))

print("x_bar =", x_bar)
print("s =", s)
print("n =", n)
print("Manual t =", t_manual)
print("ttest_1samp t =", t_stat_1)
print("Difference =", abs(t_manual - t_stat_1))

x_bar = 71.66666666666667
s = 9.547330263037681
n = 12
Manual t = -0.12094486171172245
ttest_1samp t = -0.12094486171172247
Difference = 2.7755575615628914e-17


In [4]:
levene_stat_3, levene_p_3 = stats.levene(
    poltava,
    odesa
)

print("Levene statistic:", levene_stat_3)
print("Levene p-value:", levene_p_3)

Levene statistic: 6.813202247191015
Levene p-value: 0.015979720548169964


In [5]:
levene_stat_3, levene_p_3 = stats.levene(
    poltava,
    odesa
)

print("Levene statistic:", levene_stat_3)
print("Levene p-value:", levene_p_3)

Levene statistic: 6.813202247191015
Levene p-value: 0.015979720548169964


In [6]:
t_stat_4, p_value_4 = stats.ttest_ind(
    poltava,
    lviv,
    equal_var=True
)

print("t-statistic:", t_stat_4)
print("p-value:", p_value_4)

t-statistic: -0.8380217565715362
p-value: 0.4110310299469582


In [7]:
amplitude = np.array([
    3, 3, 4, 5, 6, 7,
    7, 7, 6, 5, 4, 3
])

evening = poltava - amplitude

print("Morning:")
print(poltava)

print("\nEvening:")
print(evening)

print("\nDifference morning - evening:")
print(poltava - evening)

Morning:
[84 81 76 69 63 61 59 61 67 74 80 85]

Evening:
[81 78 72 64 57 54 52 54 61 69 76 82]

Difference morning - evening:
[3 3 4 5 6 7 7 7 6 5 4 3]


In [8]:
t_stat_5, p_value_5 = stats.ttest_rel(
    poltava,
    evening
)

print("Paired t-statistic:", t_stat_5)
print("p-value:", p_value_5)

Paired t-statistic: 10.85620296683619
p-value: 3.2341040311217473e-07


**1. Чому для однієї вибірки використовується t-критерій, а не z-критерій?**

Для одновибіркового t-критерію справжнє стандартне відхилення генеральної сукупності σ невідоме. Замість нього використовується вибіркове стандартне відхилення s, тому невизначеність оцінюється за допомогою t-розподілу.

**2. Чому неправильний вибір `equal_var` може вплинути на p-value?**

Параметр `equal_var` визначає припущення про рівність дисперсій двох груп. Якщо дисперсії насправді відрізняються, використання стандартного t-критерію може неправильно оцінити стандартну похибку та ступені свободи, що впливає на p-value. Тому перед вибором варіанта критерію доцільно перевірити дисперсії критерієм Лівена.

**3. Чому парний критерій може бути потужнішим за незалежний?**

У парному критерії аналізуються різниці всередині кожної пари. Це дозволяє врахувати спільні фактори для двох пов'язаних вимірювань і зменшити вплив варіації між парами. У результаті тест безпосередньо перевіряє середню різницю між пов'язаними спостереженнями.

**4. Чи узгоджується критерій Лівена з порівнянням `.std()`?**

Для Полтави та Одеси стандартні відхилення відрізняються, а критерій Лівена також дав статистично значущий результат (p ≈ 0.016), тому формальний тест узгоджується з помітною різницею розкиду. Для Полтави та Львова критерій Лівена дав p ≈ 0.546, тобто статистично значущої різниці дисперсій не виявлено. Просте порівняння `.std()` може показати різницю чисел, але саме по собі не визначає її статистичну значущість.
