In [6]:
import numpy as np
print(np.__version__)

2.5.3


In [8]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])

print(a)
print("shape:", a.shape)
print("dtype:", a.dtype)

[1 2 3 4 5]
shape: (5,)
dtype: int64


In [9]:
# Завдання 1
# Варіант 8 — Полтава

temps = np.array([-5, -4, 1, 10, 16, 19, 21, 20, 14, 8, 1, -3])

days_in_month = np.array([31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31])

month_numbers = np.arange(1, 13)

print("Температури Полтави:")
print(temps)
print("shape:", temps.shape)
print("dtype:", temps.dtype)

print("\nКількість днів у місяцях:")
print(days_in_month)
print("shape:", days_in_month.shape)
print("dtype:", days_in_month.dtype)

print("\nНомери місяців:")
print(month_numbers)
print("shape:", month_numbers.shape)
print("dtype:", month_numbers.dtype)

Температури Полтави:
[-5 -4  1 10 16 19 21 20 14  8  1 -3]
shape: (12,)
dtype: int64

Кількість днів у місяцях:
[31 28 31 30 31 30 31 31 30 31 30 31]
shape: (12,)
dtype: int64

Номери місяців:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,)
dtype: int64


In [10]:
# Завдання 2

# 1. Переведення температури з °C у °F
temps_f = temps * 9 / 5 + 32

print("Температура у °F:")
print(temps_f)


# 2. Знаходимо місяці, де температура > 15°C
warm_months = temps > 15

print("\nБулевий масив:")
print(warm_months)

# Кількість днів у теплих місяцях
warm_days = days_in_month[warm_months]

print("\nДні у місяцях, де температура > 15°C:")
print(warm_days)

print("Всього днів тепліше 15°C:", warm_days.sum())


# 3. Перевірка кількості днів у році
print("\nСума днів у році:", days_in_month.sum())
print("Чи дорівнює 365:", days_in_month.sum() == 365)

Температура у °F:
[23.  24.8 33.8 50.  60.8 66.2 69.8 68.  57.2 46.4 33.8 26.6]

Булевий масив:
[False False False False  True  True  True  True False False False False]

Дні у місяцях, де температура > 15°C:
[31 30 31 31]
Всього днів тепліше 15°C: 123

Сума днів у році: 365
Чи дорівнює 365: True


In [11]:
# Завдання 3

# 1. Найвища температура
max_temp = temps.max()
max_index = temps.argmax()

print("Найвища температура:", max_temp, "°C")
print("Індекс найтеплішого місяця:", max_index)
print("Номер найтеплішого місяця:", month_numbers[max_index])


# Найнижча температура
min_temp = temps.min()
min_index = temps.argmin()

print("\nНайнижча температура:", min_temp, "°C")
print("Індекс найхолоднішого місяця:", min_index)
print("Номер найхолоднішого місяця:", month_numbers[min_index])


# 2. Місяці з температурою нижче 0°C
below_zero = month_numbers[temps < 0]

print("\nМісяці з температурою нижче 0°C:")
print(below_zero)


# 3. Сортування температур
sorted_temps = np.sort(temps)

print("\nТемператури за зростанням:")
print(sorted_temps)

print("\nОригінальний масив temps:")
print(temps)

Найвища температура: 21 °C
Індекс найтеплішого місяця: 6
Номер найтеплішого місяця: 7

Найнижча температура: -5 °C
Індекс найхолоднішого місяця: 0
Номер найхолоднішого місяця: 1

Місяці з температурою нижче 0°C:
[ 1  2 12]

Температури за зростанням:
[-5 -4 -3  1  1  8 10 14 16 19 20 21]

Оригінальний масив temps:
[-5 -4  1 10 16 19 21 20 14  8  1 -3]


In [12]:
# Завдання 4

# Умовна кількість сонячних годин для Полтави
sun_hours = np.array([
    45, 55, 90, 130, 170, 210,
    230, 220, 160, 110, 60, 40
])

# Створюємо двовимірний масив
data = np.array([
    temps,
    days_in_month,
    sun_hours
])

print("Двовимірний масив:")
print(data)

print("\nФорма масиву:")
print(data.shape)


# Сума кожного рядка
print("\nСума кожного рядка:")
print(data.sum(axis=1))


# Середнє кожного рядка
print("\nСереднє кожного рядка:")
print(data.mean(axis=1))


# Сума кожного стовпця
print("\nСума кожного стовпця:")
print(data.sum(axis=0))

Двовимірний масив:
[[ -5  -4   1  10  16  19  21  20  14   8   1  -3]
 [ 31  28  31  30  31  30  31  31  30  31  30  31]
 [ 45  55  90 130 170 210 230 220 160 110  60  40]]

Форма масиву:
(3, 12)

Сума кожного рядка:
[  98  365 1520]

Середнє кожного рядка:
[  8.16666667  30.41666667 126.66666667]

Сума кожного стовпця:
[ 71  79 122 170 217 259 282 271 204 149  91  68]


In [13]:
# Завдання 5

# 1. Створюємо масив із двох рядків
rows = np.array([
    temps,
    days_in_month
])

print("rows:")
print(rows)

print("\nФорма rows:")
print(rows.shape)


# 2. Створюємо correction
correction = np.array([1, 0])

print("\ncorrection:")
print(correction)

print("Форма correction:")
print(correction.shape)


# 3. Спроба додавання
print("\nСпроба rows + correction:")

try:
    result = rows + correction
    print(result)
except ValueError as error:
    print("Виникла помилка:")
    print(error)


# 4. Змінюємо форму correction
correction_reshaped = correction.reshape(2, 1)

print("\ncorrection після reshape:")
print(correction_reshaped)

print("Нова форма:")
print(correction_reshaped.shape)


# Додавання після reshape
result = rows + correction_reshaped

print("\nРезультат:")
print(result)

rows:
[[-5 -4  1 10 16 19 21 20 14  8  1 -3]
 [31 28 31 30 31 30 31 31 30 31 30 31]]

Форма rows:
(2, 12)

correction:
[1 0]
Форма correction:
(2,)

Спроба rows + correction:
Виникла помилка:
operands could not be broadcast together with shapes (2,12) (2,) 

correction після reshape:
[[1]
 [0]]
Нова форма:
(2, 1)

Результат:
[[-4 -3  2 11 17 20 22 21 15  9  2 -2]
 [31 28 31 30 31 30 31 31 30 31 30 31]]


# Письмові відповіді

## Варіант 8 — Полтава

### 1. Чи можете ви пояснити різницю між shape == (12,) і shape == (1, 12)?

`shape == (12,)` означає, що масив є одновимірним і містить 12 елементів.

`shape == (1, 12)` означає, що масив є двовимірним та має 1 рядок і 12 стовпців.

Таким чином, кількість елементів однакова, але структура та кількість вимірів різні.

### 2. Чому temps[temps > 15] повертає масив іншої довжини, ніж temps?

Умова `temps > 15` створює булевий масив зі значеннями `True` або `False`.

Булева індексація залишає тільки ті елементи `temps`, для яких умова має значення `True`.

Тому результат містить лише температури, які перевищують 15°C, і його довжина може бути меншою за довжину початкового масиву.

### 3. Що станеться, якщо додати масив форми (3,) до масиву форми (3, 12)?

Виникне помилка broadcasting.

Масив `(3, 12)` має останній вимір 12, а масив `(3,)` має розмір 3.

Під час broadcasting NumPy порівнює розміри, починаючи з останнього. Числа 12 і 3 несумісні, тому додавання виконати неможливо.

### 4. Чому rows + correction спочатку дає помилку, а rows + correction.reshape(2, 1) — ні?

`rows` має форму `(2, 12)`, а `correction` має форму `(2,)`.

При додаванні NumPy порівнює останні виміри: 12 і 2. Вони несумісні, тому виникає помилка.

Після `correction.reshape(2, 1)` форма стає `(2, 1)`.

Тепер форми `(2, 12)` і `(2, 1)` сумісні для broadcasting. Значення кожного елемента `correction` додається до відповідного рядка `rows`.

Отже, `reshape(2, 1)` додає другий вимір і дозволяє NumPy правильно виконати broadcasting.